apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
spec:
  selector:
    app: my-webapp
  ports:
    - protocol: TCP
      nodePort: 31004
      port: 5002
      targetPort: 80
  type: NodePort
